[package]
name = "jq-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
getopts-macro = "0.1.4"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
time = "0.3.41"
